!$theme = "bunnings" 

'' Bunnings Defined Colours
!$BBeige = "#EEE7D8"
!$BBlue = "#007AC9"
!$BGreen = "#0D5257"
!$BRed = "#DA291C"
!$BYellow = "#F0AB80"

<style>
root {   
}
</style>


skinparam {
    DefaultTextAlignment center
    Shadowing true
}

skinparam SequenceArrow {
    Color Black
    Bordercolor Black
}

skinparam actorStyle awesome
skinparam SequenceActor {
    BackgroundColor $BBeige
    BorderColor $BGreen
}

skinparam Note {
    BorderColor $BRed
    BackgroundColor $BBeige
}

skinparam SequenceParticipant {
    BackgroundColor $BGreen
    FontColor White
    BorderColor $BGreen
}

skinparam SequenceGroup {
    BackgroundColor $BBeige
}

skinparam SequenceLifeLine {
    BackgroundColor $BBeige
    BorderColor black
}
